.gitignore
icezum/counter-8bits/Makefile
icezum/counter-8bits/README.md
icezum/counter-8bits/counter8.pcf
icezum/counter-8bits/counter8.vhdl

A binary counter is shown in the 8 leds of the Icezum Alhambra board

8 bits binary counter example for the Icezum Alhambra board

---

ghdl/ghdl.cc

You mentioned module instantiations work on the GHDL side, but that you did not add them to yosys yet. So I figured I'd try doing just that.
It seems to work with the *very* light testing I've done so far.
Things I'm not sure are correct:
* My handling of ports. I just copy-pasted the most trivial similar thing and nothing complained. So either it worked, it silently failed, or it only works in this trivial `and6` example.
* Blackboxes. If I omit the `and3` and only load `and6comp` it gives a warning about unbound modules, but completes. But in the output it show an empty module, and I'm not sure this is correct.
Unrelated: would you mind if I run `clang-format` on the code to fix the mix of tabs and spaces? That will be a nasty diff though.

add user cell

---

ghdl/ghdl.cc

This is needed for synthesizing `"zx"`

add const_ul32 support

---

src/ghdl.cc

This PR adds handling of PSL cover directives in Yosys. With the PR to support PSL cover directives in GHDL synthesis (https://github.com/ghdl/ghdl/pull/930), it should make it possible to use PSL cover directives with SymbiYosys to generate set of shortest traces required to reach all cover statements.

Handle PSL cover directives

---

src/ghdl.cc

This PR adds handling of `Id_Asr` for supporting `shift_right(signed, nat)` of numeric_std.
I've tested the handling of the shift functions. The tests will follow later, as they rely on SymbiYosys to formally verify the results. Don't know how to integrate such tests here at the moment, maybe @1138-4EB could help.

Handle Id_Asr

---

src/ghdl.cc

Adds handling of `Id_Sextend`. It's similar handled as `Id_Uextend`, with the difference that the `is_signed` parameter of `RTLIL::SigSpec::extend_u0()` is set to `true`.
As `RTLIL::SigSpec::extend_u0()` is implemented in the following way, this should work:
```c++
void RTLIL::SigSpec::extend_u0(int width, bool is_signed)
{
cover("kernel.rtlil.sigspec.extend_u0");
pack();
if (width_ > width)
remove(width, width_ - width);
if (width_ < width) {
RTLIL::SigBit padding = width_ > 0 ? (*this)[width_ - 1] : RTLIL::State::Sx;
if (!is_signed)
padding = RTLIL::State::S0;
while (width_ < width)
append(padding);
}
}
```
Tests follow later if I have a MWE.

Handle Id_Sextend

---

src/ghdl.cc

I see a few compiler warnings on gcc 9.2:
src/ghdl.cc: In function ‘Yosys::RTLIL::SigSpec get_src(std::vector<Yosys::RTLIL::Wire*>&, GhdlSynth::Net)’:
src/ghdl.cc:123:43: warning: ‘valzx’ may be used uninitialized in this function [-Wmaybe-uninitialized]
123 |           switch(((val01 >> i)&1)+((valzx >> i)&1)*2)
|                                    ~~~~~~~^~~~~
src/ghdl.cc:123:26: warning: ‘val01’ may be used uninitialized in this function [-Wmaybe-uninitialized]
123 |           switch(((val01 >> i)&1)+((valzx >> i)&1)*2)
|                   ~~~~~~~^~~~~
src/ghdl.cc:99:26: warning: ‘val’ may be used uninitialized in this function [-Wmaybe-uninitialized]
99 |           bits[i] = (val >> i) & 1 ? RTLIL::State::S1 : RTLIL::State::S0;
|                     ~~~~~^~~~~
These both appear to be …

Fix a couple of compiler warnings

---

.github/workflows/push.yml
ci.sh

After merging ghdl/ghdl#1104, docker images generated in ghdl/docker contain GHDL installations that can be used by ghdlsynth-beta, without recompiling GHDL. This PR modifies the CI workflow to take advantage of it. Execution time is reduced from 2min to 1min.
Note that merging this PR will introduce a `<=24h` delay since updates are pushed to ghdl/ghdl until the CI workflow here uses them. On the one hand, I think that's not very relevant because this CI workflow is mostly useful to catch regression issues. On the other hand, this PR includes commented code to allow building GHDL from master, instead of using the published docker image. Hence, it is straightforward to change it if required.

ci: use image with pre-built GHDL

---

.gitignore
src/ghdl.cc
testsuite/formal/abs/test_abs.sby
testsuite/formal/abs/test_abs.vhd
testsuite/formal/abs/testsuite.sh

yosys doesn't have a dedicated abs gate, so a negation+mux has to be used. I also added a formal test, so I'm reasonably certain it's correct - the extreme case of `abs(-127)` mirrors the `numeric_std` simulation code and returns the value unchanged.

Add abs gate

---

README.md

Closes #95 
I also added a small notice about the automatic download of the image when used the first time (thinking in people not familiarized with Docker). Let me know if you prefer that I remove this notice.

Fixed URL of the ghdl/synth Docker image

---

src/ghdl.cc
testsuite/formal/gates/test_pmux.sby
testsuite/formal/gates/test_pmux.vhd
testsuite/formal/gates/testsuite.sh

- for `Id_Pmux`, `IN(2+n)` corresponds to `s(n)`.
- for `$pmux`, `B[n*WIDTH-1:(n-1)*WIDTH]` corresponds to `S[n]`.
Therefore, the inputs need to be appended to the data vector in ascending order, such that `IN(2)` is assigned to `B[WIDTH-1:0]`, `IN(3)` to `B[2*WIDTH-1:WIDTH]`, etc.

Fix $pmux port order

---

src/ghdl.cc

This is a followup for [ghdl/ghdl issue 1342](https://github.com/ghdl/ghdl/issues/1342).
`ghdl --synth` works correctly for the `test_unop.vhd` testcase within, but the plugin fails to properly import the `$red_xor` cell:
```
yosys> ghdl --std=08 test_unop.vhd -e test_unop
1. Executing GHDL.
Importing module test_unop.
ERROR: Unsupported(1): instance \14 of $red_xor.
ERROR: Assert `GetSize(ports) >= it.second->port_id' failed in kernel/rtlil.cc:1416.
```
This pull request adds to the case statements of the plugin to allow the XOR reduce operator to be imported correctly.

Add reduce_xor support to the Yosys plugin

---

testsuite/ghdl-issues/issue1309b/testsuite.sh

Without `-f`, symbiyosys fails to run if the directory already exists.

Fix testsuite failing on second run

---

.gitignore
ci.sh

To allow the re-generation of `ghdl/synth:beta` (plugin), `ghdl/synth:formal` (formal) or run the testsuite (test), individually. The default option is run all. @eine

ci: add command-line arguments

---

Makefile

Support installing into $DESTDIR
This makes packaging easier for distributions as installation is usually
staged in a temporary directory when building intallable packages.
---
Allow overriding plugin installation directory
Currently we install the plugin into /usr/share since this is where yosys
loads from, however this violates the FHS as only architecture-independent
data is supposed to be installed in share.
Until this is reolved properly at least allow overriding the plugin
installation directory explicitly using make variables on the command line.
See YosysHQ/yosys#3151

Debian patches regarding DESTDIR and plugin install dir

---

src/ghdl.cc

I can't claim credit for this fix, but it solves a problem I bumped into when inferring RAM blocks.
Details of the problem, and fix, in this Yosys issue: https://github.com/YosysHQ/yosys/issues/3364
Testcase below:
```
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
package interface is
constant maxAddrBitBRAMLimit : integer := 32;
constant minAddrBit : integer := 2;
constant wordSize : integer := 32;
type ToROM is record
memAWriteEnable : std_logic;
memAAddr : std_logic_vector(maxAddrBitBRAMLimit downto minAddrBit);
memAWrite : std_logic_vector(wordSize-1 downto 0);
memBWriteEnable : std_logic;
memBAddr : std_logic_vector(maxAddrBitBRAMLimit downto minAddrBit);
memBWrite : std_logic_vector(wordSize-1 downto 0);
end record;
type FromROM is record
memARead : …
```

Fix to block RAM handling as per https://github.com/YosysHQ/yosys/issues/3364#issuecomment-1148066807

---

library/wrapper/primitives.v

This is in regards to #184.
**Changes**:
- changed VLO and VHI declaration capitalisation. Verilog is case-sensitive thus the modules couldn't be found by nextpnr even though yosys had no problem generating RTL
- changed VLO to use a `supply0` instead of a `supply1`. As per the Lattice FPGA Library reference ([PDF Download](https://www.latticesemi.com/~/media/LatticeSemi/Documents/UserManuals/EI/FPGALibrariesReferenceGuide32.pdf?document_id=50687)) VLO is supposed to output a logic 0 (PDF Page 705f.)
- changed VHI's `supply1` net name from `VSS` to `VDD` to avoid any confusion
The ecp5_versa example (with modified makefile to use local tools instead of docker) compiles successfully with these changes.

fixed VLO/VHI primitves

---

testsuite/testenv.sh

We don't have sby in Debian yet so we need to skip tests using it there.
Note this does use `exit` to bail out of the current test script entirely so we need to be careful not to have non-sby tests after one using sby.

Skip sby tests when unavailable

---

ci.sh

Hi @tgingold!
As shown in the latest workflow:
- https://github.com/ghdl/ghdl-yosys-plugin/actions/runs/12510093997/job/34900417538
The CI is failing because the HDL containers were removed from Google Cloud.
This PR updates the host from `gcr.io` to `ghcr.io`.
Cheers and Merry Christmas! :smiley: :partying_face: 
---
/cc @umarcor

Fix host of HDL containers

---

README.md
examples/icestick/leds/Manifest.py

Hdlmake may be used to perform analysis of project sources, before synthesis.
This modification shows how, with a simple example.

README.md: Use of hdlmake to replace sources analysis stage.
